mail:
    path: /mail
    defaults: {_controller: ReconBundle:User:mail}

login:
    path: /login
    defaults: {_controller: ReconBundle:User:login}

userlist:
    path: /userlist
    defaults: {_controller: ReconBundle:User:userlist}

inscription:
    path: /inscription
    defaults: { _controller: ReconBundle:User:ajouter}
    
recon_homepage:
    path:     /{id}
    defaults: { _controller: ReconBundle:Default:index }
