mail:
    path: /mail
    defaults: {_controller: ReconBundle:User:mail}

login:
    path: /login
    defaults: {_controller: ReconBundle:User:login}

inscription:
    path: /inscription
    defaults: { _controller: ReconBundle:User:ajouter}

inscriptionsuite:
    path: "/inscriptionsuite/{id}"
    defaults: {_controller: ReconBundle:User:inscriptionsuite}

situation:
    path: "/situation/{id}/{type}"
    defaults: {_controller: ReconBundle:User:situation}
    
deconnexion:
    path: /deco
    defaults: { _controller: ReconBundle:Default:unconnect }
    
recon_homepage:
    path:     /
    defaults: { _controller: ReconBundle:Default:index }
