userlist:
    resource: "ReconBundle/Controller/UserType"
    prefix: /userlist
    
inscription:
    resource: "ReconBundle/Controller/UserType"
    prefix: /ajouter

recon:
    resource: "@ReconBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation