<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUefc2ex\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUefc2ex/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUefc2ex.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUefc2ex\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUefc2ex\appProdProjectContainer(array(
    'container.build_hash' => 'Uefc2ex',
    'container.build_id' => '7befaf71',
    'container.build_time' => 1527547283,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUefc2ex');
