<?php

namespace ReconBundle\Repository;

/**
 * CSPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CSPRepository extends \Doctrine\ORM\EntityRepository
{
}
